version: 2

models:
  - name: stg_brands
    description: "This model contains information about bicycle brand names and IDs"
    columns:
      - name: brand_id
        description: "Primary key, unique identifier for each brand"
        tests:
            - unique
            - not_null
      - name: brand_name
        description: "Name given to the brand"

  - name: stg_categories
    description: "This model contains information about bicycle categories"
    columns:
      - name: category_id
        description: "Primary key, unique identifier for each category"
        tests:
            - unique
            - not_null
      - name: category_name
        description: "Category of bike"

  - name: stg_customers
    description: "This model contains information about customers"
    columns:
      - name: customer_id
        description: "Primary key, unique identifier for each customer"
        tests:
            - unique
            - not_null
      - name: customer_name
        description: "First name and last name of the customer"
      - name: city
        description: "City where the customer lives"
      - name: state
        description: "State where the customer lives"

  - name: stg_order_items
    description: "This model contains information about customers"
    columns:
      - name: order_id
        description: "Unique identifier of the order"
      - name: item_id
        description: "Unique identifier of the item"
      - name: product_id
        description: "Unique identifier of the product"
      - name: quantity
        description: "Amount of items by product id"
      - name: list_price
        description: "Price indicated in the catalogue"
      - name: discount
        description: "Reduction on a certain item"
      - name: final_price
        description: "Price after the discount have been applied"
      - name: total_order_price
        description: "Total amount of money paid for the order"

  - name: stg_orders
    description: "This model contains information about customers"
    columns:
      - name: order_id
        description: "Unique identifier of the order"
      - name: customer_id
        description: "Unique identifier of the customer"
      - name: order_status
        description: "Boolean indicating the status of the order"
      - name: order_date
        description: "Date when the order was placed"
      - name: required_date
        description: "Date indicated by the customer to receive the order"
      - name: shipped_date
        description: "Date when the order left the warehouse"
      - name: store_id
        description: "Unique identifier of the store"
      - name: staff_id
        description: "Unique identifier of the staff"
  
  - name: stg_products
    description: "This model contains information about customers"
    columns:
      - name: product_id
        description: "Unique identifier of the product"
      - name: product_name
        description: "Name of the product"
      - name: brand_id
        description: "Unique identifier of the brand"
      - name: category_id
        description: "Unique identifier of the category"
      - name: model_year
        description: "Year of the model"
      - name: list_price
        description: "Price of the product in the catalogue"

  - name: stg_staffs
    description: "This model contains information about customers"
    columns:
      - name: staff_id
        description: "Unique identifier fo staff personnel"
        tests:
            - unique
            - not_null
      - name: staff_name
        description: "Full name of the staff"
      - name: active
        description: "boolean to know if the staff is still working in the company or not"
      - name: store_id
        description: "Unique identifier of the store"
      - name: manager_id
        description: "unique identifier of the manager"

  - name: stg_stocks
    description: "This model contains information about customers"
    columns:
      - name: store_id
        description: "Unique identifier of the store"
      - name: product_id
        description: "Unique identifier of the product"
      - name: quantity
        description: "Sum of products in the store"

  - name: stg_stores
    description: "This model contains information about customers"
    columns:
      - name: store_id
        description: "Unique identifier of the store"
        tests:
            - unique
            - not_null
      - name: store_name
        description: "Name of the store"
      - name: city
        description: "City where the store is located"
      - name: state
        description: "State where the store is located"
      - name: zip_code
        description: "Zip code where the store is located"
      