version: 2

sources:
  - name: airbnb
    schema: airbnb
    tables:
      - name: listings

  - name: googles_analytics_4
    schema: google_analytics_4
    tables:
      - name: events_20210131
      
  - name: google_sheets
    schema: google_sheets
    tables:
      - name: account_manager_region_mapping

  - name: sales_database
    schema: sales_database
    tables:
      - name: feedback
      - name: payment
      - name: product
      - name: order
      - name: order_item
      - name: seller
      - name: user
  - name: cas_final
    schema: cas_final
    tables:
      - name: src_brands
      - name: src_categories
      - name: src_customers
      - name: src_order_items
      - name: src_orders
      - name: src_products
      - name: src_staffs
      - name: src_stocks
      - name: src_stores